# Generated by Django 6.0.2 on 2026-02-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title/name', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('property_type', models.CharField(blank=True, help_text='Type: Villa, Cabin, House, Condo, etc.', max_length=100, null=True)),
                ('bedrooms', models.IntegerField(default=1, help_text='Number of bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, help_text='Number of bathrooms', max_digits=3)),
                ('max_guests', models.IntegerField(default=2, help_text='Maximum number of guests')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Nightly rental price', max_digits=10)),
                ('address', models.CharField(blank=True, help_text='Full street address', max_length=500, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities (e.g., WiFi,Pool,Kitchen)', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is this property available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='Assign location after importing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.location')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
