"""
API URLs

WHAT THIS FILE DOES:
- Routes API endpoints
- Registers ViewSets with router
- Creates RESTful URL patterns

TOPICS TO LEARN:
- Django REST Framework routers
- ViewSet registration
- API URL patterns
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import LocationViewSet, PropertyViewSet


# ==================== CREATE ROUTER ====================

router = DefaultRouter()
# EXPLANATION:
# - DefaultRouter automatically creates URL patterns for ViewSets
# - Generates: list, detail, custom actions


# ==================== REGISTER VIEWSETS ====================

router.register(r'locations', LocationViewSet, basename='location')
# EXPLANATION:
# - r'locations' = URL prefix
# - LocationViewSet = ViewSet class
# - basename='location' = Name for URL patterns
# 
# Creates:
# - GET /api/locations/ → list (LocationViewSet.list())
# - GET /api/locations/1/ → detail (LocationViewSet.retrieve())
# - GET /api/locations/autocomplete/ → custom action


router.register(r'properties', PropertyViewSet, basename='property')
# Creates:
# - GET /api/properties/ → list
# - GET /api/properties/1/ → detail
# - GET /api/properties/?location=Miami → filtered list


# ==================== URL PATTERNS ====================

urlpatterns = [
    path('', include(router.urls)),
    # EXPLANATION:
    # - Includes all URLs generated by the router
    # - '' means no additional prefix
]


"""
ROUTERS EXPLAINED:

Router = Automatically generates URL patterns for ViewSets

from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register('items', ItemViewSet)

Generates:
- /items/ → list
- /items/<pk>/ → detail
- /items/<pk>/custom/ → custom action


VIEWSET ACTIONS TO URLS:

ViewSet Method → HTTP Method → URL
list()         → GET         → /items/
create()       → POST        → /items/
retrieve()     → GET         → /items/1/
update()       → PUT         → /items/1/
partial_update() → PATCH     → /items/1/
destroy()      → DELETE      → /items/1/


CUSTOM ACTIONS TO URLS:

@action(detail=False)
def custom(self, request):
    ...

→ GET /items/custom/


@action(detail=True)
def custom(self, request, pk):
    ...

→ GET /items/1/custom/


BASENAME:

router.register('items', ItemViewSet, basename='item')

Used for reverse URL lookup:
reverse('item-list') → /items/
reverse('item-detail', kwargs={'pk': 1}) → /items/1/


EXAMPLE API URLS:

After this configuration:

GET /api/locations/
→ LocationViewSet.list()
→ Returns all locations

GET /api/locations/1/
→ LocationViewSet.retrieve(pk=1)
→ Returns location with ID 1

GET /api/locations/autocomplete/?q=Miami
→ LocationViewSet.autocomplete()
→ Returns autocomplete results

GET /api/properties/
→ PropertyViewSet.list()
→ Returns all properties

GET /api/properties/?location=Miami
→ PropertyViewSet.list() with filtering
→ Returns properties in Miami

GET /api/properties/1/
→ PropertyViewSet.retrieve(pk=1)
→ Returns property with ID 1 (full details)
"""