# Generated by Django 6.0.2 on 2026-02-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload property image', upload_to='property_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/cover image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
