# Generated by Django 6.0.2 on 2026-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name (e.g., Miami Beach)', max_length=200, unique=True)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(help_text='State or province', max_length=100)),
                ('country', models.CharField(default='USA', help_text='Country name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the location', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
    ]
